config/routes.rb
Rails.application.routes.draw do
  resources :tuzos
  resources :user_locations
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  get 'categories/index'
  get 'categories/show'
  get 'categories/new'
  get 'signup', to: 'users#new'
  resources :users
  resources :categories
  resources :articles
  resources :articles do
    # member do
    #   put 'like' => 'articles#vote'
    # end
    resources :likes
  end
  post '/update_coordinates', to: 'locations#update_coordinates'

  get 'signup', to: "users#new"
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root "articles#index"
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6 }, uniqueness: { case_sensitive: true }
  validates :content, presence: true
  belongs_to :user
  has_one_attached :image
  has_many :article_categories
  has_many :categories, through: :article_categories
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  scope :recent, -> { order('created_at DESC').limit(4) }
  scope :most_rated, -> {
      left_joins(:likes)
        .group(:id)
        .order('COUNT(likes.id) DESC')
  }

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy vote]
  before_action :require_signin, except: %i[index show]
  before_action :set_coordinates, only: [:index]

  def index
    @articles = Article.all
    @recent_articles = Article.recent
    @most_rated_articles = Article.most_rated
    @weather_info = WeatherService.fetch_weather_and_image(@coordinates[0], @coordinates[1])

    if @weather_info.present?
    latitude = @coordinates[0]
    longitude = @coordinates[1]
    city = @weather_info[:city_name][:city] rescue nil

      if city.present? && latitude.present? && longitude.present?
        UserLocation.create(latitude: latitude, longitude: longitude, city: city)
      end
    end
  end

   # GET /articles/1
  # GET /articles/1.json
  def show
    @likers = @article.likers
    @current_like = current_user.likes.find_by(article_id: @article.id) if current_user
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit; end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.new(article_params)

    if @article.save
      flash[:success] = 'Article was successfully created.'
      redirect_to @article
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    if @article.update(article_params)
      flash[:success] = 'Article was successfully updated.'
      redirect_to @article
    else
      render :edit
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    redirect_to articles_url
    flash[:danger] = 'Article was successfully destroyed.'
  end

  def vote
    if !current_user.liked? @article
      @article.liked_by current_user
    elsif current_user.liked? @article
      @article.unliked_by current_user
    end
  end


  private

  def save_location_to_db(location_data)
    return unless location_data[:latitude].present? && location_data[:longitude].present?
    puts "****************Hello**************************"
    Rails.logger.info "**********************************************Error********************************"
    UserLocation.create(
      latitude: location_data[:latitude],
      longitude: location_data[:longitude],
      city: location_data[:city_name],
    )
  rescue => e
      Rails.logger.error "Failed to save location: #{e.message}"
  end

  def set_coordinates
    @coordinates = session[:coordinates] || [25.276987, 55.296249] # Default coordinates
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content, :image, :user_id, category_ids: [])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_category_articles.html.erb
<div class="category-show__container__flex">
  <% if obj.empty? %>
      <div class="empty-message">
          <h6>No article in this category you can <%= link_to 'create a new one', new_article_path %></h6>
      </div>
  <% end %>
    <% obj.each do |article| %>
        <div class="item">
            <div class="image">
                <%= image_tag article.image %>
            </div>
            <div class="content">
                <% if article.categories.any? %>
                <h4 class="content__category"><%= render article.categories %></h3>
                <% end %>
                <h4 class="content__title"><%= link_to article.title , article_path(article) %></h3>
                <p class="content__body"><%= truncate(article.content, length:200, separator:' ') %></p>
                <%= link_to 'read more', article_path(article) %>
            </div>
        </div>
   <% end %>
</div>

app/views/articles/_first_article.html.erb
<% obj.each do |article| %>
    <%= image_tag(article.image.first) %>
    <% if article.categories.any? %>
        <p><%= render article.categories.first %></p>
    <% end %>
    <%= link_to article.title.first , article_path(article) %>
    <%= article.content.first %>
<% end %>

app/views/articles/_form.html.erb
<div class="form form--mid">
  <div class="form__container">
  <h2>Create article</h2>
    <%= form_for(@article, data: { turbo: false }) do |f| %>
     <%= render 'shared/errors', object: @article %>
          <div class="input-box">
            <%= f.text_field :title %>
            <span>Title</span>
            <i></i>
          </div>
          <div class="input-box">
            <%= f.text_area :content %>
            <span>content</span>
            <i></i>
          </div>
          <div class="input-box">
            <%= f.file_field :image %>
            <span>Image</span>
            <i></i>
          </div>

          <div class="check-box">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
            <%= cb.label(class: "checkbox-inline") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          
          </div>
          <%= f.submit "Create Article", class: "btn btn--mid" %>
    <% end %>
  </div>
</div>

app/views/articles/_most_rated_article.html.erb
<% if obj.image.attached? %>
      <div class="slides__bg">
            
             <%= image_tag obj.image, class: "slides__img" %>
            <div class="slides__overlay">
                  <div class="slides__title" id="rated_title">
                  <%=  link_to obj.title, article_path(obj), class:"title-link" %>
                  </div>
                  <div class="slides__content">
                  <%= truncate(obj.content, length:100, separator:' ') %>
                  </div>
            </div>

      </div>
<% end %>   

app/views/articles/_news.html.erb
<div class="news">
      <div class="news__header">
         <ul class="li">News</ul>
         <ul class="li">Magazine</ul>
         <ul class="li">Sports</ul>
         <ul class="li">indie</ul>
      </div>
      <div class="news__content">
      <div class="video">
      Lorem ipsum dolor sit, amet consectetur adipisicing elit. Asperiores iusto reprehenderit quas expedita quos delectus eaque eum dicta atque repudiandae. Placeat maiores, quasi, repudiandae ex vitae rerum atque quos quas labore dicta numquam delectus fugit expedita iste excepturi ad odio non est ipsam beatae. A provident debitis deserunt fugiat amet cumque nostrum dolore quisquam ipsam optio magni quaerat earum, quibusdam voluptatem quasi harum maxime repellat minus! Voluptas magnam optio veritatis dolore quasi totam nostrum, tempore, veniam ipsa accusamus doloribus, alias excepturi illum omnis?
      </div>
      <div class="highlight">
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti.</div>
      </div>
</div>

app/views/articles/_recent_article.html.erb
<div class="row">
    <% obj.each do |article| %>
        <div class="desk-3 tab-land-4 tab-port-6 phone-12">
            <div class="recent__container">
                <% if article.image.attached? %>
                    <%= image_tag article.image, class: "recent__img" %>
                <% end %>
                    <div class="recent__content">
                        <% if article.categories.any? %>
                            <%= render article.categories %>
                        <% end %>
                        <div class="recent__title">
                            <%= link_to article.title , article_path(article) %>
                        </div>
                    </div>
            </div>
        </div>
    <%end%>
</div>

app/views/articles/_slider.html.erb
<div data-controller="slider" class="slider">
    <div class="slides">
        <% @most_rated_articles.each do |mr_article| %>
          <%= render 'articles/most_rated_article', obj: mr_article %>
        <% end %>
    </div>
    <div class="dots">
        <% @most_rated_articles.each_with_index do |mr_article, index| %>
          <button data-action="click->slider#goToSlide" data-slider-target="dot" data-index="<%= index %>"></button>
        <% end %>
    </div>
</div>

app/views/articles/_weather.html.erb
<div class="weather-card">
<img class="city-image" src="<%= @weather_info[:city_image][:image_url] %>" alt="<%= @weather_info[:city_name] %>">
<div class="weather-overlay">
  <div class="weather-info">
    <img class="weather-icon" src="<%= @weather_info[:weather_icon] %>" alt="weather icon">
    <div class="temp-info">
      <span class="temperature"><%= @weather_info[:weather_data]["main"]["temp"]- 273.15).round(1 %>&#xb0;C</span>
      <span class="humidity"><%= @weather_info[:weather_data]["main"]["humidity"] %>%</span>
    </div>
  </div>
  <p>
    Photo by 
    <%= link_to @weather_info[:city_image][:photographer], @weather_info[:city_image][:photographer_url], target: "_blank" %>
    on <%= link_to 'Pixabay', 'https://pixabay.com/', target: "_blank" %>
  </p>
  </div>
</div>

app/views/articles/index.html.erb
<div class="home" data-controller="geolocation" data-action="geolocation#updateCoordinates">
   
   <div class="row">
   
      <div class="desk-12 tab-port-12 tab-land-12 phone-12">
         <div class="home__top">
            <div class="row">
               <div class="desk-9 tab-land-9 tab-port-12 phone-12">
                  <div class="left">
                     <%= render 'slider', obj: @most_rated_articles %>
                  </div>
               </div>
               <div class="desk-3 tab-land-3 tab-port-12 phone-12">
                 <%= render 'articles/weather', obj: @weather_info %>
               </div>
            </div>
         </div>
      </div>
   </div>
   <div class="row">
      <div class="desk-12 tab-port-12 tab-land-12 phone-12">
      <div class="recent">
         <%= render 'recent_article', obj:@recent_articles %>
      </div>
      </div>
   </div>    
</div>

app/views/articles/new.html.erb
 <div class="container">
   <%= render 'form', article: @article %>
 </div>

app/views/articles/show.html.erb
<div class="show">
    <h1 align="center">
      <%= @article.title %>
    </h1>
    <div class="show__container">
        <div class="bg-image ">
        <%= image_tag @article.image %>
        </div>
        
        <div class="content">
          <p>
          <%= @article.content %>
          </p>
        </div>

        <div class="likes">
            <% if current_user %>
                <% if @current_like %>
                    <div>
                      <span>
                        <p>
                          <%= button_to "Unlike", article_like_path(@article, @current_like), class:"btn btn--unlike", method: :delete %>
                        </p>
                      </span>
                    </div>
                <% else %>
                    <div>
                      <span>
                        <p>
                          <%= button_to "like" ,article_likes_path(@article), class:"btn btn--like" %>
                        </p>
                      </span>
                    </div>
                <% end %>
            <% end %>
            <span class="likes__count">
              <%= pluralize(@likers.size, "like")%>
            </span>
            <p>
              <strong>Author:</strong>
              <%= @article.user.name %>
            </p>
            <% if @article.categories.any? %>
                <div class="category">
                    <p>
                        <span class="category__title">Categories: </span>
                        <%= render @article.categories %>
                    </p>
                </div>
            <% end %>
<% if current_user %>
            <%= button_to 'Delete this article', article_path(@article), class:"btn btn--danger", method: :delete, data: { confirm: 'Are you sure?' } %>
       <% end %>
            </div>
    </div>
<!--<%= link_to 'Edit', edit_article_path(@article) %> |-->
<!--<%= link_to 'Back', articles_path %>-->
</div>