config/routes.rb
Rails.application.routes.draw do
  resources :tuzos
  resources :user_locations
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  get 'categories/index'
  get 'categories/show'
  get 'categories/new'
  get 'signup', to: 'users#new'
  resources :users
  resources :categories
  resources :articles
  resources :articles do
    # member do
    #   put 'like' => 'articles#vote'
    # end
    resources :likes
  end
  post '/update_coordinates', to: 'locations#update_coordinates'

  get 'signup', to: "users#new"
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root "articles#index"
end

app/models/user_location.rb
class UserLocation < ApplicationRecord
    puts "User location"
end

app/controllers/user_locations_controller.rb
class UserLocationsController < ApplicationController
  before_action :set_user_location, only: %i[ show edit update destroy ]

  # GET /user_locations or /user_locations.json
  def index
    @user_locations = UserLocation.all
  end

  # GET /user_locations/1 or /user_locations/1.json
  def show
  end

  # GET /user_locations/new
  def new
    @user_location = UserLocation.new
  end

  # GET /user_locations/1/edit
  def edit
  end

  # POST /user_locations or /user_locations.json
  def create
    @user_location = UserLocation.new(user_location_params)

    respond_to do |format|
      if @user_location.save
        format.html { redirect_to @user_location, notice: "User location was successfully created." }
        format.json { render :show, status: :created, location: @user_location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_locations/1 or /user_locations/1.json
  def update
    respond_to do |format|
      if @user_location.update(user_location_params)
        format.html { redirect_to @user_location, notice: "User location was successfully updated." }
        format.json { render :show, status: :ok, location: @user_location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_locations/1 or /user_locations/1.json
  def destroy
    @user_location.destroy!

    respond_to do |format|
      format.html { redirect_to user_locations_path, status: :see_other, notice: "User location was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_location
      @user_location = UserLocation.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def user_location_params
      params.expect(user_location: [ :latitude, :longitude, :city ])
    end
end

app/helpers/user_locations_helper.rb
module UserLocationsHelper
end

app/views/user_locations/_form.html.erb
<%= form_with(model: user_location) do |form| %>
  <% if user_location.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_location.errors.count, "error") %> prohibited this user_location from being saved:</h2>

      <ul>
        <% user_location.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :latitude, style: "display: block" %>
    <%= form.text_field :latitude %>
  </div>

  <div>
    <%= form.label :longitude, style: "display: block" %>
    <%= form.text_field :longitude %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/user_locations/_user_location.html.erb
<div id="<%= dom_id user_location %>">
  <p>
    <strong>Latitude:</strong>
    <%= user_location.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= user_location.longitude %>
  </p>

  <p>
    <strong>City:</strong>
    <%= user_location.city %>
  </p>

   <p>
    <strong>Time:</strong>
    <%= user_location.created_at.in_time_zone(+3) %>
  </p>

</div>

app/views/user_locations/edit.html.erb
<% content_for :title, "Editing user location" %>

<h1>Editing user location</h1>

<%= render "form", user_location: @user_location %>

<br>

<div>
  <%= link_to "Show this user location", @user_location %> |
  <%= link_to "Back to user locations", user_locations_path %>
</div>

app/views/user_locations/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "User locations" %>

<h1>User locations</h1>

<div id="user_locations">
  <% @user_locations.each do |user_location| %>
    <%= render user_location %>
    <p>
      <%= link_to "Show this user location", user_location %>
    </p>
  <% end %>
</div>

<%= link_to "New user location", new_user_location_path %>

app/views/user_locations/new.html.erb
<% content_for :title, "New user location" %>

<h1>New user location</h1>

<%= render "form", user_location: @user_location %>

<br>

<div>
  <%= link_to "Back to user locations", user_locations_path %>
</div>

app/views/user_locations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_location %>

<div>
  <%= link_to "Edit this user location", edit_user_location_path(@user_location) %> |
  <%= link_to "Back to user locations", user_locations_path %>

  <%= button_to "Destroy this user location", @user_location, method: :delete %>
</div>