config/routes.rb
Rails.application.routes.draw do
  resources :tuzos
  resources :user_locations
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  get 'categories/index'
  get 'categories/show'
  get 'categories/new'
  get 'signup', to: 'users#new'
  resources :users
  resources :categories
  resources :articles
  resources :articles do
    # member do
    #   put 'like' => 'articles#vote'
    # end
    resources :likes
  end
  post '/update_coordinates', to: 'locations#update_coordinates'

  get 'signup', to: "users#new"
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6 }, uniqueness: { case_sensitive: true }
  validates :content, presence: true
  belongs_to :user
  has_one_attached :image
  has_many :article_categories
  has_many :categories, through: :article_categories
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  scope :recent, -> { order('created_at DESC').limit(4) }
  scope :most_rated, -> {
      left_joins(:likes)
        .group(:id)
        .order('COUNT(likes.id) DESC')
  }

end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, uniqueness: { case_sensitive: true }
    validates :priority, presence: true, uniqueness: true
    has_many :article_categories
    has_many :articles, through: :article_categories
    scope :priority_cat, -> { order('priority').limit(7) }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/tuzo.rb
class Tuzo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: { case_sensitive: false },
                    format: /\A\S+@\S+\z/
  has_many :articles, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_articles, through: :likes, source: :article
  
    def self.authenticate(email, password)
        user = User.find_by(email: email)
        user && user.authenticate(password)
    end
end

app/models/user_location.rb
class UserLocation < ApplicationRecord
    puts "User location"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :require_signin, only: [:create, :destroy]
    before_action :set_article, only: [:create, :destroy]
    def create
        @article.likes.create!(user: current_user)
        flash[:success] = 'Glad! you liked it!'
        redirect_to @article
      end
    
      def destroy
        like = current_user.likes.find(params[:id])
        like.destroy
        flash[:danger] = 'Sorry! you unliked it!'
        redirect_to @article
      end

    private 
    def set_article 
        
        @article = Article.find(params[:article_id])
    end
end

app/controllers/tuzos_controller.rb
class TuzosController < ApplicationController
  before_action :set_tuzo, only: %i[ show edit update destroy ]

  # GET /tuzos or /tuzos.json
  def index
    @tuzos = Tuzo.all
  end

  # GET /tuzos/1 or /tuzos/1.json
  def show
  end

  # GET /tuzos/new
  def new
    @tuzo = Tuzo.new
  end

  # GET /tuzos/1/edit
  def edit
  end

  # POST /tuzos or /tuzos.json
  def create
    @tuzo = Tuzo.new(tuzo_params)

    respond_to do |format|
      if @tuzo.save
        format.html { redirect_to @tuzo, notice: "Tuzo was successfully created." }
        format.json { render :show, status: :created, location: @tuzo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tuzo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tuzos/1 or /tuzos/1.json
  def update
    respond_to do |format|
      if @tuzo.update(tuzo_params)
        format.html { redirect_to @tuzo, notice: "Tuzo was successfully updated." }
        format.json { render :show, status: :ok, location: @tuzo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tuzo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tuzos/1 or /tuzos/1.json
  def destroy
    @tuzo.destroy!

    respond_to do |format|
      format.html { redirect_to tuzos_path, status: :see_other, notice: "Tuzo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tuzo
      @tuzo = Tuzo.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def tuzo_params
      params.expect(tuzo: [ :name, :email, :phone ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tuzos_helper.rb
module TuzosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flashes.html.erb
<div class="flash-message">
  <% flash.each do |key, value|  %>
    <%= content_tag(:p, value, :class => "flash #{key}") %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
   <div class="footer logo">
     <h2 class="logo logo--medium">WriTEhUb<span class="logo__dot"></span></h2>
   </div>
   <div class="footer terms">
     <p>Privacy Policy Terms & Conditions <span class="footer__policy">Copy rights 2014.
     All rights reserved</span></p>
   </div>
   <div class="footer social">
     connect with us
      <ul class="footer__icons">
            <li>
                <a href="https://web.facebook.com/ibunhabibu/">
                <i class="fab fa-facebook-square"></i>
                </a>
            </li>
            <li>
                <a href="https://twitter.com/Ibunhabibu">
                <i class="fab fa-twitter-square"></i>
                </a>
            </li>
            
            <li>
                <a href="https://www.instagram.com/ibunhabibu/">
                <i class="fab fa-instagram"></i>
                </a>
            </li>
      </ul>
   </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Writehub" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :application, "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body data-controller="geolocation" id="location">
    <div class="wrapper">
      <%= render 'layouts/header/nav' %>
      <%= render 'layouts/flashes' %>
        <div class="main-content">
          <%= yield %>
        </div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/header/_dropdown.html.erb
<ul class="dropdown-menu">
    <li>
      <%= link_to 'Articles', articles_path, class: "header__menu__item" %>
    </li>
    <li>
      <%= link_to 'Categories', categories_path, class: "header__menu__item" %>
    </li>
</ul>

app/views/layouts/header/_image_mega_menu.html.erb
<div class="mega-menu blog">
                    <div class="content">
                      <div class="col">
                        <a href="#" class="image-wrapper">
                          <span class="img">
                          <img src="https://picsum.photos/400?random=3" alt="blog mega">
                          </span>
                        </a>
                        <h2>Title</h2>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                         Fugit reiciendis blanditiis eveniet laborum hic dicta, 
                        quo aspernatur molestiae ullam esse.</p>
                        <a href="#" class="read-more">read more...</a>
                      </div>
                      <div class="col">
                        <a href="#" class="image-wrapper">
                          <span class="img">
                          <img src="https://picsum.photos/400?random=2" alt="blog mega">
                          </span>
                        </a>
                        <h2>Title</h2>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                         Fugit reiciendis blanditiis eveniet laborum hic dicta.</p>
                        <a href="#" class="read-more">read more...</a>
                      </div>
                        <div class="col">
                        <a href="#" class="image-wrapper">
                          <span class="img">
                          <img src="https://picsum.photos/400?random=4" alt="blog mega">
                          </span>
                        </a>
                        <h2>Title</h2>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                         Fugit reiciendis blanditiis eveniet laborum hic dicta, 
                        quo aspernatur molestiae ullam esse.</p>
                        <a href="#" class="read-more">read more...</a>
                      </div>
                        <div class="col">
                        <a href="#" class="image-wrapper">
                          <span class="img">
                          <img src="https://picsum.photos/400?random=5" alt="blog mega">
                          </span>
                        </a>
                        <h2>Title</h2>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                         Fugit reiciendis blanditiis eveniet laborum hic dicta, 
                        quo aspernatur molestiae ullam esse.</p>
                        <a href="#" class="read-more">read more...</a>
                      </div>
                    </div>
                  </div>

app/views/layouts/header/_mega_menu.html.erb
<div class="mega-menu">
                    <div class="content">
                      <div class="col">
                        <section>
                          <h2>Featured 1</h2>
                          <a href="#" class="image-wrapper">
                            <span class="img">
                              <img src="https://picsum.photos/400?random=1" alt="random image">
                            </span>
                          </a>
                          <p>lore ipsum dolor sit amet Lorem, ipsum dolor.</p>
                        </section>
                      </div>
                      <div class="col">
                        <section>
                          <h2>Featured 2</h2>
                          <ul class="mega-links">
                            <li><a href="#">Item1</a></li>
                            <li><a href="#">Item2</a></li>
                            <li><a href="#">Item3</a></li>
                            <li><a href="#">Item4</a></li>
                            <li><a href="#">Item5</a></li>
                            <li><a href="#">Item5</a></li>
                          </ul>
                        </section>
                      </div>
                      <div class="col">
                        <section>
                          <h2>Featured 3</h2>
                          <ul class="mega-links">
                            <li><a href="#">Item1</a></li>
                            <li><a href="#">Item2</a></li>
                            <li><a href="#">Item3</a></li>
                            <li><a href="#">Item4</a></li>
                            <li><a href="#">Item5</a></li>
                            <li><a href="#">Item5</a></li>
                          </ul>
                        </section>
                      </div>
                      <div class="col">
                        <section>
                          <h2>Featured 4</h2>
                          <ul class="mega-links">
                            <li><a href="#">Item1</a></li>
                            <li><a href="#">Item2</a></li>
                            <li><a href="#">Item3</a></li>
                            <li><a href="#">Item4</a></li>
                            <li><a href="#">Item5</a></li>
                            <li><a href="#">Item5</a></li>
                          </ul>
                        </section>
                      </div>
                    </div>
                  </div>

app/views/layouts/header/_nav.html.erb
<header class="header" data-controller="humburger">
   
    <div class="logo-menu">
      <div class="humburger"  data-action="click->humburger#toggleNav">
        <span class="line1"></span>
        <span class="line2"></span>
        <span class="line3"></span>
      </div>
      <h2 class="logo">WriTEhUb<span class="logo__dot"></span></h2>
    </div>
    <nav data-humburger-target="nav">
        <ul class="menu" data-action="click->humburger#closeNav">
        <li>
          <%= link_to "Home", root_path, class: "menu__item" %>
        </li>
        
        <% Category.priority_cat.each do |category| %>
                <li>
                  <%= link_to category.name, category_path(category), class: "menu__item " %>
                </li>
        <% end %>  
        <% if current_user %>
          <li class="create">
            <%= link_to 'create category', new_category_path, class: "header__menu__item" %>
          </li>
          <li class="create">
              <%= link_to 'create article', new_article_path, class: "header__menu__item dashboard" %>
          </li>
          <li>
            <%= link_to 'Logout', logout_path, data: { turbo_method: :delete }, class: "header__menu__item" %>
          <li>
        <% else %>
          <li>
            <%= link_to 'Login', login_path, class: "header__menu__item header__menu__item--line" %>
          </li>
          <li>
            <%= link_to 'Register', new_user_path, class: "header__menu__item" %>
          </li>
        <% end %>
        </ul>
    </nav>
    <div class="header__user">
      <ul>
        
        <li><i class="fas fa-search "></i></li>
      </ul>
    </div>
</header>

app/views/layouts/header/_sublist.html.erb
 <ul class="menu-right">
    <li><a href="#" class="menu-item">Item3.1</a></li>
    <li><a href="#" class="menu-item">Item3.2</a></li>
    <li><a href="#" class="menu-item">Item3.3</a></li>
    <li><a href="#" class="menu-item">Item3.3</a></li>
</ul>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <section  id="errors">
      <header>
        <h2>
        Oops! Your form could not be saved.
        </h2>
        <h3>
          Please correct the following 
          <%= pluralize(object.errors.count, "error") %>
        </h3>
        <ul>
            <% object.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
        </ul>
      </header>
    </section>
  <% end %>